RedditClone/config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#               new_session GET    /session/new(.:format)                                                                   sessions#new
#                   session DELETE /session(.:format)                                                                       sessions#destroy
#                           POST   /session(.:format)                                                                       sessions#create
#                      subs GET    /subs(.:format)                                                                          subs#index
#                           POST   /subs(.:format)                                                                          subs#create
#                   new_sub GET    /subs/new(.:format)                                                                      subs#new
#                  edit_sub GET    /subs/:id/edit(.:format)                                                                 subs#edit
#                       sub GET    /subs/:id(.:format)                                                                      subs#show
#                           PATCH  /subs/:id(.:format)                                                                      subs#update
#                           PUT    /subs/:id(.:format)                                                                      subs#update
#                           DELETE /subs/:id(.:format)                                                                      subs#destroy
#                     posts POST   /posts(.:format)                                                                         posts#create
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :subs
  
  resources :posts, only: %i(new show create edit update destroy) do
    resources :comments, only: [:new]
  end

  resources :comments, only: %i(index show edit create update destroy)

end

RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord

    validates :title, :author_id, presence: true

    belongs_to :author,
        class_name: :User

    has_many :postsubs, dependent: :destroy, inverse_of: :post

    has_many :subs, through: :postsubs

    has_many :comments


end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :ensure_logged_in, only: [:create, :edit, :new, :update, :destroy]

    def show
        @post = Post.find_by(id: params[:id])
        render :show
    end

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id

        if @post.save
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
        render :edit
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to subs_url
        else
            flash.now[:errors] = @post.errors.full_messages
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to subs_url
    end


    private

    def post_params
        params.require(:post).permit(:title, :url, :content, sub_ids: [])
    end


end

RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/app/views/posts/_form.html.erb
<% if action == :edit %>
    <% method_url = post_url(post) %>
    <% verb = "patch" %>
    <% button_text = "Save Post" %>
<% else %>
    <% method_url = posts_url %>
    <% verb = "post" %>
    <% button_text = "Add Post" %>
<% end %>



<form action="<%= method_url %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="<%= verb %>">

    <label for="title"> Title
        <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>

    <label for="url">URL
        <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>

    <label for="content">Content
        <textarea name="post[content]" cols="30" rows="10" value="<%= @post.content %>"></textarea>
    </label>
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
    <label for="">
        <input 
            type="checkbox" 
            name="post[sub_ids][]" 
            value="<%= sub.id %>"
            <%= "checked" if @post.sub_ids.include?(sub.id) %>>
        <%= sub.title %>
    </label>
    <br>
    <% end %>

    <button type="submit"><%= button_text %></button>
</form>

RedditClone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>


<%= render "form", action: :edit, post: @post %>

RedditClone/app/views/posts/new.html.erb
<h1>Create a Post</h1>


<%= render 'form', action: :new, post: @post %>

RedditClone/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2>By <%= @post.author.username %></h2>

<h2>Content:</h2>
<span><%= @post.content %></span> <br>
<span><%= @post.url %></span>

<h2>Subs</h2>

<ul>
<% @post.subs.each do |sub| %>
    <li>
    <a href="<%=sub_url(sub)%>"><%= sub.title %></a>
    </li>
<% end %>
</ul>

<h2>Comments</h2>
<a href="<%=new_post_comment_url(@post.id)%>">Add a new comment!</a>

<% unless @post.comments.empty? %> 
<ul>

<% @post.comments.where(parent_comment_id: nil).each do |comment| %>
    <li>
    <a href="<%=comment_url(comment)%>"><%= comment.content %></a>
        <ul>
            <% if comment.child_comments %>
                <% comment.child_comments.each do |child| %>
                    <li><a href="<%= comment_url(child) %>"><%= child.content %></a></li>
                <% end %>
            <% end %>
        </ul>
    </li>
<% end %>
</ul>
<% end %>
<a href="<%=edit_post_url(@post)%>">Edit</a>